### ISSUE TITLE
Remove Pull Request Workflow

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Header#46]
**Description**
The automatically generated workflow files contain a workflow for when a pull request is opened. We will not be using this feature. Because we're not using it, the following bits of code can be removed:

```yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - test
```

and 

```yml
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0501B9D0F }}
          action: "close"
```

**Why it's Important**
We don't want these parts of the workflow triggering when we open pull requests.
